// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM8Yu8uQAZCDty0Ft0PiDkQnseb69Gshw',
    appId: '1:1048686640180:web:6b6d6cf65a2495de279e61',
    messagingSenderId: '1048686640180',
    projectId: 'deardiary-dc10e',
    authDomain: 'deardiary-dc10e.firebaseapp.com',
    storageBucket: 'deardiary-dc10e.appspot.com',
    measurementId: 'G-5ZQQGV098W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxogHk2A4Y22EHAgT1Ss3YJgYG4rsIMM',
    appId: '1:1048686640180:android:5fe0723f988e1e40279e61',
    messagingSenderId: '1048686640180',
    projectId: 'deardiary-dc10e',
    storageBucket: 'deardiary-dc10e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYm2Cbz5q_yh8Yz-3ZHhv-FN1FPdpUL8k',
    appId: '1:1048686640180:ios:f71ea86b825b1bd0279e61',
    messagingSenderId: '1048686640180',
    projectId: 'deardiary-dc10e',
    storageBucket: 'deardiary-dc10e.appspot.com',
    iosClientId: '1048686640180-9pk7fq6k9dafltcu5fiqjtkq9drcftq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydiaryApp',
  );
}
